--- !ditz.rubyforge.org,2008-03-06/project 
name: pyKEGGParser
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: pyKEGGParser
- !ditz.rubyforge.org,2008-03-06/component 
  name: to_discuss
- !ditz.rubyforge.org,2008-03-06/component 
  name: test
releases: []

